Rolling 9 dependencies (#66)
Roll third_party/glslang/ 6c479796f..ebf634bca (1 commit)

https://github.com/KhronosGroup/glslang/compare/6c479796f6e4...ebf634bcaa3e

$ git log 6c479796f..ebf634bca --date=short --no-merges --format='%ad %ae %s'
2019-12-12 greg Update spriv-tools known good

Roll third_party/googletest/ 78fdd6c00..5b162a79d (7 commits)

https://github.com/google/googletest/compare/78fdd6c00b8f...5b162a79d49d

$ git log 78fdd6c00..5b162a79d --date=short --no-merges --format='%ad %ae %s'
2019-12-12 absl-team Googletest export
2019-12-11 absl-team Googletest export
2019-12-10 absl-team Googletest export
2019-12-06 misterg Googletest export
2019-11-17 krystian.kuzniarek remove MSVC workaround: warning 4355
2019-11-14 krystian.kuzniarek remove MSVC workaround: error C2665
2019-11-22 krystian.kuzniarek remove g++ 2.95.0 workaround: no space after first comma in macros

Roll third_party/re2/ 6a86f6b3f..7470f4d02 (1 commit)

https://github.com/google/re2/compare/6a86f6b3f4a6...7470f4d02753

$ git log 6a86f6b3f..7470f4d02 --date=short --no-merges --format='%ad %ae %s'
2019-12-13 junyer std::is_pod<> was deprecated in C++20.

Roll third_party/shaderc/ 2fc6bac86..979ad21e8 (2 commits)

https://github.com/google/shaderc/compare/2fc6bac865f4...979ad21e8422

$ git log 2fc6bac86..979ad21e8 --date=short --no-merges --format='%ad %ae %s'
2019-12-12 rharrison Implement a C++ only version for ForEachCombinedImageSamplers (#936)
2019-12-11 9856269+sarahM0 Add missing APIs for GLSL in Dawn (#934)

Roll third_party/spirv-tools/ 00ca4e5bd..96354f504 (4 commits)

https://github.com/KhronosGroup/SPIRV-Tools/compare/00ca4e5bdfdb...96354f5047bf

$ git log 00ca4e5bd..96354f504 --date=short --no-merges --format='%ad %ae %s'
2019-12-12 afdx spirv-fuzz: Fuzzer pass to merge blocks (#3097)
2019-12-11 stevenperron Start SPIRV-Tools v2020.1
2019-12-11 stevenperron Finalize SPIRV-Tools v2019.5
2019-12-11 stevenperron Update CHANGES

Roll third_party/vulkan-guide/ 18276f292..a7954147c (1 commit)

https://github.com/KhronosGroup/Vulkan-Guide/compare/18276f29232d...a7954147c8c7

$ git log 18276f292..a7954147c --date=short --no-merges --format='%ad %ae %s'
2019-12-12 46493288+sfricke-samsung Added YouTube to whitelist for travis CI build (#13)

Roll third_party/vulkan-hpp/ 3f82338d9..7da1c8baf (2 commits)

https://github.com/KhronosGroup/Vulkan-Hpp/compare/3f82338d9fee...7da1c8baf0f2

$ git log 3f82338d9..7da1c8baf --date=short --no-merges --format='%ad %ae %s'
2019-12-16 asuessenbach Samples: Explicitly set vk::PipelineMultisampleStateCreateInfo::rasterizationSamples (#459)
2019-12-12 asuessenbach Introduce default initializers for member variables, simplify default values for constructor arguments (#455)

Roll third_party/vulkan-loader/ 1830f45ee..206979855 (3 commits)

https://github.com/KhronosGroup/Vulkan-Loader/compare/1830f45ee904...2069798558ec

$ git log 1830f45ee..206979855 --date=short --no-merges --format='%ad %ae %s'
2019-12-12 lenny loader: Add custom terminator to tool properties
2019-12-10 caio.oliveira build: Fix Vulkan registry detection
2019-12-11 lenny codegen: Fix crash in tooling info terminator

Roll third_party/vulkan-validationlayers/ 49cc6797a..2b19f3916 (17 commits)

https://github.com/KhronosGroup/Vulkan-ValidationLayers/compare/49cc6797ad33...2b19f3916726

$ git log 49cc6797a..2b19f3916 --date=short --no-merges --format='%ad %ae %s'
2019-12-12 mark tests: Add tests for DescTemplates fixes and new VUIDs
2019-12-12 mark objlifetimes: Fix CreateDescUpdateTemplates object val
2019-12-13 mark build: Update glslang & VulkanTools known-good IDs
2019-11-29 geecandrey corechecks: Invalid error message in vkCmdPipelineBarrier
2019-12-10 mark tests: Add positive test for tooling ext query
2019-12-10 mark chassis: Support tooling queries in khronos layer
2019-12-10 mark chassis: Add physicaldevice support for tools info API
2019-12-10 mark stateless: Update for new struct_type_array case
2019-12-10 mark chassis: Implement GetPhysicalDeviceProcAddr layer func
2019-12-09 jeremyk layers: Fix issue 1416
2019-12-12 jzulauf layers: Improve const shared pointer handling
2019-12-12 mark corechecks: Correct swapchain validation error text
2019-12-10 tony gpu: Add validation for VK_KHR_buffer_device_address
2019-12-10 jbolz tests: Add tests for VK_KHR_buffer_device_address
2019-12-10 jbolz layers: Add VK_KHR_buffer_device_address support
2019-12-04 tobias.hector tests: Added tests for new vkAllocateMemory validation
2019-11-28 tobias.hector layers: Introduce validation for vkAllocateMemory VUIDs

Created with:
  roll-dep third_party/effcee third_party/glm third_party/glslang third_party/googletest third_party/re2 third_party/shaderc third_party/spirv-cross third_party/spirv-headers third_party/spirv-tools third_party/tinyxml2 third_party/vulkan-docs third_party/vulkan-guide third_party/vulkan-headers third_party/vulkan-hpp third_party/vulkan-loader third_party/vulkan-validationlayers